/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GenerateInitMaterials } from "./Utils";
import gsap from "gsap";

export function Bottle(props) {
  const { cristalMaterial, sodaMaterial, brandMaterial } =
    GenerateInitMaterials();
  const { nodes, materials } = useGLTF("/Bottle.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Bottle"
          castShadow
          receiveShadow
          geometry={nodes.Bottle.geometry}
          material={cristalMaterial}
        />
        <mesh
          name="Soda"
          castShadow
          receiveShadow
          geometry={nodes.Soda.geometry}
          material={sodaMaterial}
        />
        <mesh
          name="Brand"
          castShadow
          receiveShadow
          geometry={nodes.Brand.geometry}
          material={brandMaterial}
        />
        <mesh
          name="Cap"
          castShadow
          receiveShadow
          geometry={nodes.Cap.geometry}
          material={brandMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Bottle.glb");
